hrm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.conf import settings
from django.conf.urls.static import static


# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(selfself, request, user):
        return '/index/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'isd.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', include('vietskill.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

vietskill/schedule/urls.py
# -*- coding: utf-8 -*-

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
from django.conf.urls import patterns, url
from vietskill.schedule import views

urlpatterns = patterns(
    '',
    url(r'^$', views.meeting_index, name='meeting'),
    url(r'^meeting/new', views.meeting_new, name='new_meeting'),
    url(r'^meeting/(?P<pk>[0-9]+)/delete/$', views.meeting_delete, name='delete_meeting'),
    url(r'^meeting/(?P<pk>[0-9]+)/update/$', views.meeting_update, name='update_meeting'),
    url(r'^meeting/', views.meeting_index, name='meeting'),

    url(r'^plan/new', views.plan_new, name='new_plan'),
    url(r'^plan/(?P<pk>[0-9]+)/update/$', views.plan_update, name='update_plan'),
    url(r'^plan/(?P<pk>[0-9]+)/delete/$', views.plan_delete, name='delete_plan'),
    url(r'^plan/', views.plan_index, name='plan'),

    url(r'^event/update', views.event_update_or_create, name='update_event'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.event_delete, name='delete_event'),
    url(r'^events/json$', views.event_json, name='fetch_events'),
    url(r'^event/', views.event_index, name='event'),

    url(r'^teaching_schedule/update', views.schedule_update_or_create, name='update_schedule'),
    url(r'^teaching_schedule/(?P<pk>[0-9]+)/delete/$', views.schedule_delete, name='delete_schedule'),
    url(r'^teaching_schedule/', views.schedule_index, name='teaching_schedule'),
)

vietskill/urls.py
from django.conf.urls import patterns, include, url
from vietskill import views
from vietskill import schedule

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),

    url(r'^teaching-day/$', views.teaching_day, name='teaching_day'),
    url(r'^online-day/$', views.online_day, name='online_day'),
    url(r'^absent-day/$', views.absent_day, name='absent_day'),
    url(r'^mistake/$', views.mistake, name='mistake'),

    url(r'^profile-all/$', views.profile_all, name='profile_all'),
    url(r'^profile-detail/(?P<pk>[0-9]+)/$', views.profile_detail, name='profile_detail'),
    url(r'^profile/add/$', views.profile_add, name='profile_add'),
    url(r'^profile/(?P<pk>[0-9]+)/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^profile/(?P<pk>[0-9]+)/delete/$', views.profile_delete, name='profile_delete'),

    url(r'^recruit/add/$', views.recruit_add, name='recruit_add'),
    url(r'^recruit/(?P<pk>[0-9]+)/edit/$', views.recruit_edit, name='recruit_edit'),
    url(r'^recruit/(?P<pk>[0-9]+)/delete/$', views.recruit_delete, name='recruit_delete'),
    url(r'^recruit/$', views.recruit_index, name='recruit'),

    url(r'^assess/$', views.assessment, name='assess'),
    url(r'^assess/add/$', views.assess_add, name='assess_add'),
    url(r'^assess/(?P<pk>[0-9]+)/edit/$', views.assess_edit, name='assess_edit'),
    url(r'^assess/(?P<pk>[0-9]+)/delete/$', views.assess_delete, name='assess_delete'),
    # Include urls for schedule
    url(r'^schedule/', include(schedule.urls))
)

vietskill/models.py
from django.db import models
from datetime import datetime


class StaffProfile(models.Model):
    name = models.CharField(max_length=128)
    birthday = models.DateField()
    SEX_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    position = models.CharField(max_length=128)
    email = models.EmailField()
    address = models.CharField(max_length=128)
    phone_number = models.CharField(max_length=11)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.name
"""
    def age(self):
        today = date.today()
        return today.year - StaffProfile.birthday.year
"""


class Statistic(models.Model):
    staff = models.ForeignKey(StaffProfile)
    num_teaching_days = models.IntegerField()
    days_off = models.IntegerField()
    num_mistakes = models.IntegerField()


class Meeting(models.Model):
    date_time = models.DateTimeField(default=datetime.now, blank=True)
    purpose = models.TextField()
    location = models.CharField(max_length=100)
    note = models.TextField()


class MeetingPaticipant(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    staff_id = models.IntegerField(default=-1, blank=True)
    meeting = models.ForeignKey(Meeting)


class Plan(models.Model):
    start_date = models.DateField()
    due_date = models.DateField()
    duration = models.IntegerField()
    content = models.TextField()
    STATUS_CHOICES = (
        ('1', 'Completed'),
        ('2', 'In Progress'),
        ('3', 'New')
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    staffs = models.ManyToManyField(StaffProfile)


class Event(models.Model):
    date = models.DateTimeField()
    title = models.CharField(max_length=100)
    content = models.TextField()
    location = models.CharField(max_length=100)


class TeachingSchedule(models.Model):
    staff = models.ForeignKey(StaffProfile)
    DAY_CHOICES = (
        ('1', 'Monday'),
        ('2', 'Tuesday'),
        ('3', 'Wednesday'),
        ('4', 'Thursday'),
        ('5', 'Friday'),
        ('6', 'Saturday'),
        ('7', 'Sunday')
    )
    day = models.CharField(max_length=3, choices=DAY_CHOICES)
    SESSION_CHOICES = (
        ('1', '7:15 - 9:00'),
        ('2', '9:30 - 11:15'),
        ('3', '12:30 - 14:15'),
        ('4', '14:45 - 16:30')
    )
    session = models.CharField(max_length=1, choices=SESSION_CHOICES)
    SUBJECT_CHOICES = (
        ('1', 'Master of Ceremonies'),
        ('2', 'Life Skill'),
        ('3', 'Art'),
        ('4', 'Soft Skill'),
        ('5', 'Copy Editing'),
        ('6', 'Communication'),
        ('7', 'Culture'),
        ('8', 'Marketing'),
        ('9', 'Presentation'),
    )
    subject = models.CharField(max_length=1, choices=SUBJECT_CHOICES)
    classes = models.CharField(max_length=20)
    room = models.CharField(max_length=10)

    def __repr__(self):
        return "<ScheduleItem day: %r session: %r>" % (self.day, self.session)

    @property
    def get_subject(self):
        if self.subject:
            return dict(TeachingSchedule.SUBJECT_CHOICES)[self.subject]
        else:
            return ""

    @property
    def get_session(self):
        if self.session:
            return dict(TeachingSchedule.SESSION_CHOICES)[self.session]
        else:
            return ""

    @property
    def get_day(self):
        if self.day:
            return dict(TeachingSchedule.DAY_CHOICES)[self.day]
        else:
            return ""


class StaffShift(models.Model):
    staff = models.ForeignKey(StaffProfile)
    date = models.DateField()
    time = models.CharField(max_length=30)
    num_shift = models.IntegerField()
    location = models.CharField(max_length=100)


class Assessment(models.Model):
    staff = models.ForeignKey(StaffProfile)
    content = models.TextField()
    date = models.DateField()
    assess_point = models.IntegerField()

    def __str__(self):
        return self.content


class Recruitment(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    release_date = models.DateField()
    expiry_date = models.DateField()
    office = models.CharField(max_length=50)
    position = models.CharField(max_length=50)

    def __str__(self):
        return self.title

vietskill/schedule/models.py
from django.db import models

# Create your models here.

vietskill/forms.py
from django import forms
from vietskill.models import StaffProfile, Recruitment, Assessment


class ProfileForm(forms.ModelForm):

    class Meta:
        model = StaffProfile
        fields = ('name', 'birthday', 'sex', 'position', 'email', 'address', 'phone_number', 'picture')


class RecruitmentForm(forms.ModelForm):

    class Meta:
        model = Recruitment
        fields = ('title', 'content', 'release_date', 'expiry_date')


class AssessmentForm(forms.ModelForm):

    class Meta:
        model = Assessment
        fields = ('staff', 'content', 'assess_point', 'date')

vietskill/schedule/forms.py
# -*- coding: utf-8 -*-

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
import datetime

from django import forms
from vietskill import models

DT_FORMAT = "%m/%d/%Y_%H:%M"
D_FORMAT = "%m/%d/%Y"


class MeetingForm(forms.Form):
    """Custom form to process Meeting POST request
    """
    location = forms.CharField(label='Location', max_length=100)
    attendants = forms.CharField(label='Attendants')
    purpose = forms.CharField(label='Purpose')
    date = forms.CharField(label='Date')
    time = forms.CharField(label='Time')

    def clean(self):
        """Validate form data
        """
        date = self.cleaned_data.get('date')
        time = self.cleaned_data.get('time')
        dt_str = date + '_' + time
        dt = datetime.datetime.strptime(dt_str, DT_FORMAT)
        self.cleaned_data['datetime'] = dt

        return self.cleaned_data


class PlanForm(forms.Form):
    """Custom form to process Plan POST request
    """
    start_date = forms.CharField(label='Start date', max_length=100)
    due_date = forms.CharField(label='End date')
    content = forms.CharField(label='Content')
    status = forms.CharField(label='Status')
    staffs = forms.CharField(label='Time')

    def clean(self):
        """Validate form data
        """
        start_date_str = self.cleaned_data.get('start_date')
        due_date_str = self.cleaned_data.get('due_date')
        self.cleaned_data['start_date'] = datetime.datetime.strptime(start_date_str, D_FORMAT)
        self.cleaned_data['due_date'] = datetime.datetime.strptime(due_date_str, D_FORMAT)

        return self.cleaned_data


class EventForm(forms.Form):
    """Custom form to process Event POST request
    """
    id = forms.IntegerField(required=False)
    date = forms.CharField(label='Date')
    title = forms.CharField(label='Title')
    content = forms.CharField(label='Content')
    location = forms.CharField(label='Location')

    def clean(self):
        """Validate form data
        """
        miliseconds = self.cleaned_data.get('date')
        self.cleaned_data['date'] = datetime.datetime.fromtimestamp(float(miliseconds[:-3]))
        #import ipdb; ipdb.set_trace()
        event_id = self.cleaned_data.get('id')
        self.cleaned_data['id'] = event_id if event_id != 0 else None
        return self.cleaned_data


class ScheduleForm(forms.Form):
    """Custom form to process Schedule POST request
    """
    id = forms.IntegerField(required=False)
    staff = forms.CharField(label='Staff')
    day = forms.CharField(label='Day')
    session = forms.CharField(label='Session')
    subject = forms.CharField(label='Subject')
    classes = forms.CharField(label='Class')
    room = forms.CharField(label='Room')

    def clean(self):
        """Validate form data
        """
        return self.cleaned_data

vietskill/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from vietskill.models import StaffProfile, Recruitment, Assessment
from vietskill.forms import ProfileForm, RecruitmentForm, AssessmentForm
from vietskill import models
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'vietskill/index.html', {})


def about(request):
    return render(request, 'vietskill/about.html', {})


def profile_all(request):
    profile_list = StaffProfile.objects.all().order_by("name")
    context_dict = {'profiles': profile_list}
    return render(request, 'vietskill/profile_all.html', context_dict)


def profile_detail(request, pk):
    profile = get_object_or_404(StaffProfile, pk=pk)
    context_dict = {'profile': profile}
    return render(request, 'vietskill/profile_detail.html', context_dict)


@login_required
def profile_add(request):
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=True)
            return redirect('vietskill.views.profile_detail', pk=profile.pk)
        else:
            print form.errors
    else:
        form = ProfileForm()
    # form = ProfileForm()
    context_dict = {'form': form}
    return render(request, 'vietskill/profile_add.html', context_dict)


@login_required
def profile_edit(request, pk):
    profile = get_object_or_404(StaffProfile, pk=pk)
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            profile = form.save(commit=True)
            return redirect('vietskill.views.profile_detail', pk=profile.pk)
        else:
            print form.errors
    else:
        form = ProfileForm(instance=profile)
    context_dict = {'form': form}
    return render(request, 'vietskill/profile_edit.html', context_dict)


@login_required
def profile_delete(request, pk):
    profile = get_object_or_404(StaffProfile, pk=pk)
    profile.delete()
    return redirect('vietskill.views.profile_all')


#Statistics
def teaching_day(request):
    return render(request, 'statistics/teaching_day.html', {})


def online_day(request):
    return render(request, 'statistics/online_day.html', {})


def absent_day(request):
    return render(request, 'statistics/absent_day.html', {})


def mistake(request):
    return render(request, 'statistics/mistake.html', {})


def recruit_index(request):
    posts = Recruitment.objects.all().order_by('release_date')
    context_dict = {'posts': posts}
    return render(request, 'vietskill/recruitment.html', context_dict)


@login_required
def recruit_add(request):
    if request.method == "POST":
        form = RecruitmentForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return recruit_index(request)
    else:
        form = RecruitmentForm()
    return render(request, 'vietskill/recruitment_edit.html', {'form': form})


@login_required
def recruit_edit(request, pk):
    post = get_object_or_404(models.Recruitment, pk=pk)
    if request.method == "POST":
        form = RecruitmentForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('vietskill.views.recruit_index')
    else:
        form = RecruitmentForm(instance=post)
    return render(request, 'vietskill/recruitment_edit.html', {'form': form})


@login_required
def recruit_delete(request, pk):
    post = get_object_or_404(Recruitment, pk=pk)
    post.delete()
    return redirect('vietskill.views.recruit_index')


def assessment(request):
    assess = Assessment.objects.all().order_by('staff')
    context_dict = {'assess': assess}
    return render(request, 'vietskill/assess.html', context_dict)


@login_required
def assess_add(request):
    if request.method == "POST":
        form = AssessmentForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return assessment(request)
    else:
        form = AssessmentForm()
    return render(request, 'vietskill/assess_edit.html', {'form': form})


@login_required
def assess_edit(request, pk):
    assess = get_object_or_404(models.Assessment, pk=pk)
    if request.method == "POST":
        form = AssessmentForm(request.POST, instance=assess)
        if form.is_valid():
            form.save()
            return redirect('vietskill.views.assessment')
    else:
        form = AssessmentForm(instance=assess)
    return render(request, 'vietskill/assess_edit.html', {'form': form})


@login_required
def assess_delete(request, pk):
    assess = get_object_or_404(Assessment, pk=pk)
    assess.delete()
    return redirect('vietskill.views.assessment')

templates/vietskill/about.html
{% extends "vietskill/base.html" %}

{% load staticfiles %}

{% block title %} About Us {% endblock %}

{% block content %}

    {# Page Heading #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">About Us</h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'index' %}">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-info"></i> About Us
                </li>
            </ol>
        </div>
    </div>{# /.row  #}

    <div class="row">
        <div class="col-lg-12 text-center">
            <img src="{% static "images/about-us.jpg" %}" class="img-responsive center-block" width="800" alt=""/> <!-- Images -->
        </div>
    </div>

{% endblock %}

templates/vietskill/profile_add.html
{% extends "vietskill/base.html" %}

{% load staticfiles %}

{% block title %} New Profile {% endblock %}

{% block content %}

    {# Page Heading #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">New Profile</h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'index' %}">Dashboard</a>
                </li>
                <li>
                    <i class="fa fa-group"></i> <a href="{% url 'profile_all' %}">Staff Profile</a>
                </li>
                <li class="active">
                    <i class="fa fa-plus"></i> New Profile
                </li>
            </ol>
        </div>
    </div>{# /.row  #}

    <div class="row">
        <div class="col-md-3 col-lg-3">
        </div>
        <div class="col-md-6 col-lg-6 text-center">
            <form method="POST" class="profile-form form-horizontal" role="form">
                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_name">Name:</label>

                    <div class="col-sm-8">
                        <input id="id_name" class="form-control" maxlength="128" name="name" type="text"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_birthday">Birthday:</label>

                    <div class="col-sm-8">
                        <input id="id_birthday" class="form-control" name="birthday" type="text"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_sex">Sex:</label>

                    <div class="col-sm-8">
                        <select id="id_sex" class="form-control" name="sex">
                            <option value="" selected="selected">---------</option>
                            <option value="M">Male</option>
                            <option value="F">Female</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_position">Position:</label>

                    <div class="col-sm-8">
                        <input id="id_position" class="form-control" maxlength="128" name="position" type="text"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_email">Email:</label>

                    <div class="col-sm-8">
                        <input id="id_email" class="form-control" maxlength="75" name="email" type="email"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_address">Address:</label>

                    <div class="col-sm-8">
                        <input id="id_address" class="form-control" maxlength="128" name="address" type="text"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_phone_number">Phone number:</label>

                    <div class="col-sm-8">
                        <input id="id_phone_number" class="form-control" maxlength="11" name="phone_number" type="text"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_picture">Picture:</label>

                    <div class="col-sm-8">
                        <input id="id_picture" name="picture" type="file"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="save btn btn-primary">Save</button>
                        <button type="submit" class="save btn btn-default">Cancel</button>
                    </div>
                </div>
                {# {{ form.as_p }}#}
            </form>
        </div>
        <div class="col-md-3 col-lg-3">
        </div>
    </div>{# /.row  #}

{% endblock %}

templates/vietskill/profile_detail.html
{% extends "vietskill/base.html" %}

{% load staticfiles %}

{% block title %} Staff Profile {% endblock %}

{% block content %}

    {# Page Heading #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Staff Profile</h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'index' %}">Dashboard</a>
                </li>
                <li>
                    <i class="fa fa-group"></i> <a href="{% url 'profile_all' %}">Staff Profile</a>
                </li>
                <li class="active">
                    <i class="fa fa-user"></i> Profile detail
                </li>
            </ol>
        </div>
    </div>{# /.row  #}

    <div class="row">
        <div class="col-lg-12 text-right">
            {% if user.is_authenticated %}
            <a href="{% url 'profile_edit' pk=profile.pk %}" class="btn btn-warning" role="button">
                <span class="glyphicon glyphicon-pencil"></span> Edit profile</a>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                <span class="glyphicon glyphicon-remove"></span> Delete profile
            </button>
            {% endif %}

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title text-left" id="myModalLabel">Delete profile</h4>
                        </div>
                        <div class="modal-body">
                            <p class="text-center">Are you sure you want to delete this profile?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <a href="{% url 'profile_delete' pk=profile.pk %}" class="btn btn-danger" role="button">
                                OK</a>
                            {# <button type="button" class="btn btn-primary">OK</button>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>{# /.row  #}
    <br>
    <div class="row">
        <div class="col-md-2 col-lg-2">
        </div>
        <div class="col-md-8 col-lg-8 text-center">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped table-condensed">
                    <thead>
                    <tr>
                        <th class="text-center">Staff #{{ profile.pk }}</th>
                        <th class="text-center" colspan="2" l>Information</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td rowspan="6">
                            <img src="{{ profile.picture.url }}"/>

                            <h3>
                                <a href="{% url 'vietskill.views.profile_detail' pk=profile.pk %}">{{ profile.name }}</a>
                            </h3>
                        </td>
                        <td><strong>Birthday</strong></td>
                        <td>{{ profile.birthday }}</td>
                    </tr>
                    <tr>
                        <td><strong>Sex</strong></td>
                        <td>{{ profile.get_sex_display }}</td>
                    </tr>
                    <tr>
                        <td><strong>Position</strong></td>
                        <td>{{ profile.position }}</td>
                    </tr>
                    <tr>
                        <td><strong>Email</strong></td>
                        <td>{{ profile.email }}</td>
                    </tr>
                    <tr>
                        <td><strong>Address</strong></td>
                        <td>{{ profile.address }}</td>
                    </tr>
                    <tr>
                        <td><strong>Phone Number</strong></td>
                        <td>{{ profile.phone_number }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-2 col-lg-2">
        </div>
    </div>

{% endblock %}

templates/vietskill/recruitment_edit.html
{% extends "vietskill/base.html" %}

{% load staticfiles %}

{% block title %} Recruitment {% endblock %}

{% block content %}

    {# Page Heading #}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Recruitment</h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="{% url 'index' %}">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-rocket"></i> <a href="{% url 'recruit' %}">Recruitment</a>
                </li>
            </ol>
        </div>
    </div>{# /.row  #}

    <div class="row">
        {% comment %}        <div class="col-md-3 col-lg-3">
        </div>
        <div class="col-md-6 col-lg-6 text-center">
            <form method="POST" class="recruitment-form form-horizontal" role="form" action=".">
                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_title">Title:</label>

                    <div class="col-sm-8">
                        <input id="id_title" class="form-control" maxlength="50" name="title" type="text" value=""/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_content">Content:</label>

                    <div class="col-sm-8">
                        <textarea cols="40" id="id_content" class="form-control" name="content" rows="10"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_release_date">Title:</label>

                    <div class="col-sm-8">
                        <input id="id_release_date" class="form-control" name="release_date" type="text" value=""/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-4" for="id_expiry_date">Title:</label>

                    <div class="col-sm-8">
                        <input id="id_expiry_date" class="form-control" name="expiry_date" type="text" value=""/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="save btn btn-primary">Save</button>
                        <a href="{% url 'recruit' %}"><button type="submit" class="save btn btn-default">Cancel</button></a>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3 col-lg-3">

        </div>{% endcomment %}
        <div class="col-lg-12">
            <form method="POST" class="recruitment-form" action=".">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-primary">Save</button>
                <a href="{% url 'recruit' %}"><button type="submit" class="save btn btn-default">Cancel</button></a>
            </form>
        </div>
    </div>

{% endblock %}